<div id="sidebar">
    <h3>Síguenos</h3>
    <ul class="sidemenu">
        <li><a href="http://blog.quepimquepam.com">Blog</a></li>
        <li><a rel="nofollow" href="http://www.facebook.com/#!/pages/QuePimQuePamcom/132709583416652?ref=sgm">Facebook</a></li>
        <li><a rel="nofollow" href="http://twitter.com/quepimquepam">Twitter</a></li>
        <li><a rel="nofollow" href="http://www.linkedin.com/company/quepimquepam-development-s.l.?trk=fc_badge">LinkedIn</a></li>
    </ul>

    <h3>Clientes</h3>
    <ul class="sidemenu">
        <li><a rel="nofollow" href="http://www.emagister.com">Emagister.com</a></li>
        <li><a rel="nofollow" href="http://www.gsicommerce.com">GSI Commerce International</a></li>
        <li><a rel="nofollow" href="http://www.riplife.es">Riplife Gamming</a></li>
        <li><a rel="nofollow" href="http://www.alfa9.com">Alfa9</a></li>
        <li><a rel="nofollow" href="http://www.tesipro.com">Tesipro S.A.</a></li>
        <li><a rel="nofollow" href="http://www.lumenisac.es">Lumenis - Auditoría y Consultoría</a></li>
        <li><a rel="nofollow" href="http://www.tempobcn.com">TempoBCN</a></li>
        <li><a rel="nofollow" href="http://www.musicadesign.net">MusicaDesign</a></li>
        <li><a rel="nofollow" href="http://www.stevebeer.com">Steve's Beer</a></li>
        <li><a rel="nofollow" href="http://www.latamtraining.com">Latam Training</a></li>
        <li><a rel="nofollow" href="http://www.lifestyleexperiencesgroup.com">Lifestyle Experiences Group</a></li>
        <li><a rel="nofollow" href="http://www.localbilling.com">Local Billing</a></li>
        <li><a rel="nofollow" href="http://www.giulio.es">GIULIO - No comment underware</a></li>
        <li><a rel="nofollow" href="http://www.saranadal.com">Sara Nadal</a></li>
        <li><a rel="nofollow" href="http://www.flamingohotelier.com">Flamingo Hotelier</a></li>
        <li><a rel="nofollow" href="http://www.talleresperser.com">Talleres Perser</a></li>
    </ul>

    <h3>Nuestras palabras mágicas</h3>
    <p>Agile, Momentum, Pasión, Lean, StartUp, Scrum, XP, Basecamp, Continuous Integration, Continuous Deployment, Git, TDD, KISS, DRY, PHP, Zend Framework, CSS, XHTML, Javascript, jQuery, ExtJS, AJAX, Python, Erlang, Machine Learning, Data Mining, NoSQL, MySQL, Analytics, Google, Cloud Computing, Email, Hosting, Virtual Servers, MVC, Web Services, REST, XML, SOA, Comunidad, etc.</p>

    <h3>Entusiasmos</h3>
    <ul class="sidemenu">
        <li><a href="http://www.sexperiences.es">sexperiences.es</a></li>
        <li><a href="http://www.phpchampionship.com">phpchampionship.com</a></li>
    </ul>

    <h3>Danos un toque</h3>
    <p><a href="mailto:quierosabermas@quepimquepam.com">quierosabermas@quepimquepam.com</a> es siempre una buena opción, échale un ojo a <a href="http://twitter.com/quepimquepam">@quepimquepam</a>. Estamos por algún sitio más, si nos ves, saluda.</p>
</div>
